seamapi/nextlove

.github/workflows/npm-semantic-release.yml
apps/example-todo-app/package.json
packages/nextlove/bin.js
packages/nextlove/package.json
packages/nextlove/release.config.js
packages/nextlove/src/generate-route-types/index.ts
yarn.lock

- checkpoint semantic release
- typegen working with zod conversion
```ts
export interface Routes {
"/api/todo/add": {
route: "/api/todo/add"
method: "POST"
queryParams: {}
jsonBody: {
id?: string
title: string
completed?: boolean
}
commonParams: {}
jsonResponse: {
ok: boolean
}
}
"/api/todo/delete": {
route: "/api/todo/delete"
method: "DELETE"
queryParams: {}
jsonBody: {
id: string
}
commonParams: {}
jsonResponse: {
ok: boolean
}
}
"/api/todo/get": {
route: "/api/todo/get"
method: "GET"
queryParams: {
id: string
}
jsonBody: never
commonParams: {}
jsonResponse: {
ok: boolean
todo: {
id: string
}
}
}
}
export type RouteResponse<Path extends keyof Routes> =
Routes[Path]["jsonResponse"]
export type RouteRequestBody<Path extends keyof Routes> =
Routes[Path]["jsonBody"] & …
```

Generate a Routes.ts file with types (good for client libraries), Support for Semantic Release

---

apps/example-todo-app/package.json
package.json
packages/nextlove/src/lib/parse-routes-in-package.ts
yarn.lock

- Fix to use the correct join from path library for a normalized filepath
- Installed cpy package in order for the copy of .next into dist to work on any OS
Fix: #32

fix: Yarn build failing on windows

---

packages/nextlove/src/generate-route-types/index.ts

This should hopefully reduce the diffs in seamapi/javascript when updating types because of the non-deterministic output.

Sort routes by name when generating types

---

packages/nextlove/package.json

Zod is directly imported by nextlove consumers, so this needs to be a peer rather than a direct dependency.

Make zod peer dependency

---

packages/nextlove/src/generate-route-types/index.ts

This enables compatibility with https://github.com/seamapi/typed-axios

fix: use type for route-types generation

---

packages/nextlove/package.json

Should be a normal dependency: https://github.com/seamapi/nextlove/blob/main/packages/nextlove/src/generate-openapi/index.ts#L6-L10

Move openapi3-ts to dependencies

---

packages/nextlove/package.json

Running the CLI tools fail without this. The CLI should probably be moved to it's own package: `nextlove-cli` so consumers do not have to deploy esbuild into production.

fix: Add esbuild-register to peerDependencies

---

packages/nextlove/bin.js
packages/nextlove/src/generate-openapi/index.ts

- Add missing apiPrefix option to type
- Correct docs for apiPrefix default value

fix: Fix docs for default api prefix

---

apps/example-todo-app/pages/api/todo/json-response-must-be-schema.ts
packages/nextlove/src/types/index.ts

`withRouteSpec()` previously didn't error if `jsonResponse` was a plain JS object.

`jsonResponse` should be a Zod schema

---

packages/nextlove/package.json

The built `index.js` was inflated from under 1MB to 25MB in v2.1.0 because Prettier was being bundled.

Reduce bundle size

---

packages/nextlove/src/generate-route-types/index.ts

The `omit` method only exists on `ZodObject` and sometimes if we use `refine` and `optional`, we will get query params that are `ZodEffects` or `ZodOptional`

Fix the filtering of query params for path params

---

packages/nextlove/src/generators/generate-openapi/fern-sdk-utils.ts
packages/nextlove/src/generators/generate-openapi/index.ts

[fern docs](https://buildwithfern.com/docs/spec/extensions)

fern meta tags

---

apps/example-todo-app/lib/middlewares/with-route-spec.ts
packages/nextlove/src/types/index.ts
packages/nextlove/src/with-route-spec/index.ts
packages/nextlove/src/with-route-spec/middlewares/with-validation.ts

This is causing problems since we often have to call `createWithRouteSpec` as a const object, which makes the list of array formats `readonly`, which prevents passing as a normal array.

switch to readonly array for array formats

---

packages/nextlove/src/generators/generate-route-types/index.ts
packages/nextlove/src/generators/lib/parse-routes-in-package.ts

New version of nextlove breaks types in Seam Connect because the internal variant of route type generation needs to include all routes.

feat: Allow including OpenAPI excluded routes in route type generation

---

packages/nextlove/src/generators/generate-route-types/index.ts

`z.union()` was breaking route type generation before this change.

fix: Allow any Zod type for `queryParams`

---

apps/example-todo-app/pages/api/todo/multiple-auth-errors-handled-by-route.ts
apps/example-todo-app/tests/api/todo/multiple-auth-errors-handled-by-route.test.ts
packages/nextlove/src/types/index.ts
packages/nextlove/src/with-route-spec/index.ts
packages/nextlove/tests/with-route-spec/basic.test.ts

not sure if this is needed, definitely feels like a bit of an early optimization. I felt like we might want the ability to override the `onMultipleAuthMiddlewareFailures` binding declared in setup params at the route level as we continue to add support for multiple auth handlers for a route. this will allow us to override the "global" handler as the route configuration will take precedence.

expose onMultipleAuthMiddlewareFailures binding on route level

---

apps/example-todo-app/pages/api/todo/add.ts
apps/example-todo-app/tests/openapi-generation/openapi-generation.test.ts
packages/nextlove/src/generators/lib/zod-openapi.ts

This should fix a validation error that we get on seam-connect:
`{ "type": "null" }` is not valid as a `oneOf` option, like here:
Instead, this PR makes so that `{ "nullable": true }` is set

Enhance OpenAPI Spec Generation for Nullable Union Types in Record Properties

---

apps/example-todo-app/pages/api/todo/add.ts
apps/example-todo-app/tests/openapi-generation/openapi-generation.test.ts
packages/nextlove/src/generators/lib/zod-openapi.ts

OpenAPI 3.0 does not have an explicit `null` type as in JSON Schema. This PR replaces it with `nullable: true` which is supported.

OpenAPI generation: `null` params should be flagged with `nullable`

---

apps/example-todo-app/pages/api/todo/add.ts
apps/example-todo-app/tests/openapi-generation/openapi-generation.test.ts
packages/nextlove/src/generators/generate-openapi/index.ts
packages/nextlove/src/generators/lib/zod-openapi.ts
packages/nextlove/src/generators/utils/dashify-object-keys.ts
packages/nextlove/src/generators/utils/prefix-keys-with-x.ts
packages/nextlove/src/generators/utils/prefix-object-keys-with-x.ts
packages/nextlove/src/types/index.ts

wrt https://github.com/seamapi/nextlove/issues/143
- **Deprecate sdkReturnValue in favour of front matter response_key**
- **Test response_key**
- **Custom front matter `description` properties should be prefixed with `x-` and in dash style `x-my-prop`**

Deprecate `sdkReturnValue` in favour of `response_key` in the front matter of the `description`

---

.github/workflows/npm-lint.yml
.github/workflows/npm-semantic-release.yml
.github/workflows/npm-test.yml
apps/example-todo-app/pages/api/todo/list.ts
apps/example-todo-app/tests/openapi-generation/openapi-generation.test.ts
packages/nextlove/bin.js
packages/nextlove/src/generators/generate-openapi/index.ts

Closes https://github.com/seamapi/nextlove/pull/115
Pretty much the title, previously generating the OpenAPI json would ignore GET if POST was defined as well. Now it generates both (and DELETE too).
Main change was to remove the filter at https://github.com/seamapi/nextlove/pull/159/files#diff-3f2c0f6d81a28b504bad9f4790e395fdf0d3fd6dd3fe8848371b3499e243abd1L179
But because request body and query definitions were checked at the route level and not the method level, this resulted in the generated spec to be wrong. i.e. generating a `requestBody` for GET and not a `parameters`.
The fix was to create a loop per method, and move the body and query defs in there instead. Looks like lots of changes, but it's just moving nesting: https://github.com/seamapi/nextlove/pull/159/files#diff-3f2c0f6d81a …

fix: allow generating GET and POST openapi spec
